
#define SPRITE_SIZE 64
#define PLAYER_NUM_SPRITES 1


#define WHITE 0xFFFF
#define BROWN 0x00FE
#define GRAY  0x5555
#define GREEN 0x0420
#define BLUE  0xF8E7
#define BLACK 0x0000
#define YELLOW 0x07FF
#define TAN   0xE71F //might be wrong

#ifndef PLAYER_H
#define PLAYER_H



unsigned int player_Sprite[PLAYER_NUM_SPRITES][SPRITE_SIZE]= {
    WHITE,WHITE,BROWN,WHITE,WHITE,BROWN,WHITE,WHITE,
    WHITE,TAN,GREEN,GREEN,GREEN,GREEN,WHITE,GRAY,
    BLUE,BLUE,BLUE,BROWN,BROWN,BROWN,GREEN,GRAY,
    WHITE,GRAY,GREEN,GREEN,TAN,GREEN,WHITE,GRAY,
    WHITE,GRAY,WHITE,TAN,TAN,TAN,TAN,WHITE,
    GREEN,GRAY,TAN,YELLOW,BLACK,TAN,BLACK,WHITE,
    WHITE,GRAY,GREEN,YELLOW,TAN,YELLOW,YELLOW,YELLOW,
    WHITE,WHITE,GREEN,GREEN,YELLOW,YELLOW,YELLOW,WHITE
};

#endif