#include "colors.h"

#ifndef TILESET_H
#define TILESET_H

#define SPRITE_SIZE 64
#define NUM_TILES 2

unsigned int tileset[NUM_TILES][SPRITE_SIZE] = {

    {WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
    WHITE,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
    WHITE,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,WHITE,
    WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
    WHITE,WHITE,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,
    WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
    WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,WHITE,WHITE,
    WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE},

    {BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,
    BLACK,BROWN,BLACK,BLACK,BLACK,BROWN,BROWN,BLACK,
    BLACK,BROWN,BLACK,BROWN,BROWN,BROWN,BROWN,BLACK,
    BLACK,BLACK,BROWN,BROWN,BROWN,BROWN,BLACK,BLACK,
    BLACK,BROWN,BLACK,BLACK,BROWN,BLACK,BROWN,BLACK,
    BLACK,BROWN,BROWN,BROWN,BROWN,BLACK,BROWN,BLACK,
    WHITE,BLACK,BROWN,BROWN,BROWN,BLACK,BLACK,WHITE,
    WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE}
    

};

#endif