
#include "colors.h"

#define SPRITE_SIZE 64
#define PLAYER_NUM_SPRITES 1


#ifndef PLAYER_H
#define PLAYER_H


uint16_t player_Sprite[PLAYER_NUM_SPRITES][SPRITE_SIZE]= {
    
    WHITE,WHITE,BROWN,WHITE,WHITE,BROWN,WHITE,WHITE,
    WHITE,TAN,GREEN,GREEN,GREEN,GREEN,WHITE,GRAY,
    BLUE,BLUE,BLUE,BROWN,BROWN,BROWN,GREEN,GRAY,
    WHITE,GRAY,GREEN,GREEN,TAN,GREEN,WHITE,GRAY,
    WHITE,GRAY,WHITE,TAN,TAN,TAN,TAN,WHITE,
    GREEN,GRAY,TAN,YELLOW,BLACK,TAN,BLACK,WHITE,
    WHITE,GRAY,GREEN,YELLOW,TAN,YELLOW,YELLOW,YELLOW,
    WHITE,WHITE,GREEN,GREEN,YELLOW,YELLOW,YELLOW,WHITE
    
};

uint16_t healthbar_Sprite[1][SPRITE_SIZE]={

    WHITE,WHITE,WHITE,BLACK,BLACK,WHITE,WHITE,WHITE,
    WHITE,WHITE,BLACK,RED,RED,BLACK,WHITE,WHITE,
    WHITE,BLACK,RED,RED,RED,RED,BLACK,WHITE,
    BLACK,RED,RED,RED,RED,RED,RED,BLACK,
    BLACK,RED,RED,RED,RED,RED,RED,BLACK,
    BLACK,RED,RED,BLACK,BLACK,RED,RED,BLACK,
    WHITE,BLACK,BLACK,WHITE,WHITE,BLACK,BLACK,WHITE,
    WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE
};

#endif